network.host: 0.0.0.0

cluster.name: ${CLUSTER_NAME}

node.name: ${NODE_NAME}

discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["192.168.0.102","192.168.0.104","192.168.0.105"]
discovery.zen.minimum_master_nodes: ${MASTER_NUM}
